/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2015-2018 Ruslan Bukin <br@bsdpad.com>
 * All rights reserved.
 * Copyright (c) 2019-2021 Mitchell Horne <mhorne@FreeBSD.org>
 * Copyright (c) 2022-2024 The FreeBSD Foundation
 *
 * Portions of this software were developed by SRI International and the
 * University of Cambridge Computer Laboratory under DARPA/AFRL contract
 * FA8750-10-C-0237 ("CTSRD"), as part of the DARPA CRASH research programme.
 *
 * Portions of this software were developed by the University of Cambridge
 * Computer Laboratory as part of the CTSRD Project, with support from the
 * UK Higher Education Innovation Fund (HEIF).
 *
 * Portions of this software were developed by Mitchell Horne
 * <mhorne@FreeBSD.org> under sponsorship from the FreeBSD Foundation.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#include "assym.inc"

#include <machine/asm.h>
#ifdef __CHERI__
#include <machine/cherireg.h>
#endif
#include <machine/cpu.h>
#include <machine/param.h>
#include <machine/pte.h>
#include <machine/riscvreg.h>
#include <machine/sbi.h>

	.globl	kernbase
	.set	kernbase, KERNBASE

	.text
/*
 * Alternate entry point. Used when booting via SBI firmware. It must be placed
 * at the beginning of the .text section. Arguments are as follows:
 *  - a0 = hart ID
 *  - a1 = dtbp
 *
 * Multiple CPUs might enter from this point, so we perform a hart lottery and
 * send the losers to mpentry.
 */
	.globl _alt_start
_alt_start:
	/* Set the global pointer */
#ifdef __CHERI__
	cmv	PTR(gp), PTR_NULL

.option push
.option nocapmode

	/*
	 * The boot loader may enter in non-capmode even though
	 * our ELF header requests capmode.  The instructions below
	 * should work in both modes.
	 */
	modesw.cap
.option pop
#else
.option push
.option norelax
	lla	gp, __global_pointer$
.option pop
#endif

	/* Pick a hart to run the boot process. */
	li	t1, 1
	LLA_PTR	PTR(t0), hart_lottery
	amoadd.w	t0, t1, 0(PTR(t0))

	/*
	 * We must jump to mpentry in the non-BSP case because the offset is
	 * too large to fit in a 12-bit branch immediate.
	 */
	beqz	t0, 1f
	j	mpentry
1:
	/* Store the boot hart */
	LLA_PTR	PTR(t0), boot_hart
	sw	a0, 0(PTR(t0))

	/*
	 * Stash the DTB pointer in the callee-saved register s4, and zero s3
	 * to indicate that we have no loader metadata.
	 */
	mv	s4, a1
	mv	s3, zero
	j	pagetables

/*
 * Main entry point. This routine is marked as the ELF entry, and is where
 * loader(8) will enter the kernel. Arguments are as follows:
 *  - a0 = modulep
 *  - a1 = ???
 *
 * It is expected that only a single CPU will enter here.
 */
	.globl _start
_start:
	/* Set the global pointer */
#ifdef __CHERI__
	MV_PTR	PTR(gp), PTR(null)

	/* Enable CHERI for U-mode */
	li	t0, SENVCFG_CRE
	csrs	senvcfg, t0
#else
.option push
.option norelax
	lla	gp, __global_pointer$
.option pop
#endif

	/*
	 * Stash modulep in the callee-saved register s3, and zero s4 to
	 * indicate that we have no DTB pointer. It is already included in the
	 * loader(8) metadata.
	 */
	MV_PTR	PTR(s3), PTR(a0)
	mv	s4, zero

	/*
	 * Set up page tables: Our goal is to enable virtual memory, doing the
	 * minimum amount of work in assembly; just what is required to
	 * bootstrap. We will construct the real page tables in C code, in
	 * pmap_bootstrap().
	 *
	 * Here we map a 1GB region starting at KERNBASE using 2MB superpages,
	 * starting from the first 2MB physical page into which the kernel was
	 * loaded.
	 *
	 * We also use an L1 entry to create a 1GB identity map (1:1 PA->VA).
	 * This is useful for two reasons:
	 *  - handling the DTB pointer passed from SBI firmware (physical addr)
	 *  - simpler construction of pagetables in pmap_bootstrap()
	 *
	 * Implementations are required to provide Sv39 mode, so we use that
	 * here and will conditionally enable Sv48 (or higher) later.
	 *
	 * We arrive here with:
	 *  s3 - modulep or zero
	 *  s4 - zero or dtbp
	 */
pagetables:
	/* Get the kernel's load address (kernstart) in s9 */
	jal	get_physmem

	/* Get PTE attribute bits in s8 */
	jal	get_pte_fixup_bits

	/* Construct 1GB Identity Map (1:1 PA->VA) */
	LLA_PTR	PTR(s1), bootstrap_pt_l1

	srli	s2, s9, L1_SHIFT	/* kernstart >> L1_SHIFT */
	andi	a5, s2, Ln_ADDR_MASK	/* & Ln_ADDR_MASK */
	li	t4, (PTE_KERN)
	or	t4, t4, s8		/* t4 |= pte bits */
	slli	s2, s2, PTE_PPN2_S	/* (s2 << PTE_PPN2_S) */
	or	t6, t4, s2

	/* Store L1 PTE entry to position */
	li	a6, PTE_SIZE
	mulw	a5, a5, a6		/* calculate L1 slot */
	ADD_PTR	PTR(t0), PTR(s1), a5
	sd	t6, (PTR(t0))		/* Store new PTE */

	/* Construct the virtual address space at KERNBASE */

	/* Add L1 entry for kernel */
	LLA_PTR	PTR(s1), bootstrap_pt_l1
	LLA_PTR	PTR(s2), bootstrap_pt_l2	/* Link to next level PN */
	srli	s2, s2, PAGE_SHIFT

	li	a5, KERNBASE
	srli	a5, a5, L1_SHIFT	/* >> L1_SHIFT */
	andi	a5, a5, Ln_ADDR_MASK	/* & Ln_ADDR_MASK */
	li	t4, PTE_V
	slli	t5, s2, PTE_PPN0_S	/* (s2 << PTE_PPN0_S) */
	or	t6, t4, t5

	/* Store L1 PTE entry to position */
	li	a6, PTE_SIZE
	mulw	a5, a5, a6
	ADD_PTR	PTR(t0), PTR(s1), a5
	sd	t6, (PTR(t0))

	/* Level 2 superpages (512 x 2MiB) */
	LLA_PTR	PTR(s1), bootstrap_pt_l2
	srli	t4, s9, L2_SHIFT	/* Div physmem base by 2 MiB */
	li	t2, Ln_ENTRIES		/* Build 512 entries */
	add	t3, t4, t2
	li	t0, (PTE_KERN | PTE_X)
	or	t0, t0, s8		/* t0 |= pte bits */
1:
	slli	t2, t4, PTE_PPN1_S	/* << PTE_PPN1_S */
	or	t5, t0, t2
	sd	t5, (PTR(s1))		/* Store PTE entry to position */
	ADDI_PTR	PTR(s1), PTR(s1), PTE_SIZE

	addi	t4, t4, 1
	bltu	t4, t3, 1b

	/* Page tables END */

	/*
	 * Set the supervisor trap vector temporarily. Enabling virtual memory
	 * may generate a page fault. We simply wish to continue onwards, so
	 * have the trap deliver us to 'va'.
	 */
	LLA_PTR	PTR(t0), va
	li	t1, KERNBASE
	sub	t1, t1, s9
	ADD_PTR	PTR(t0), PTR(t0), t1
	csrw	PTR_CSR(stvec), PTR(t0)

	/* Set page tables base register */
	LLA_PTR	PTR(s2), bootstrap_pt_l1
	srli	s2, s2, PAGE_SHIFT
	li	t0, SATP_MODE_SV39
	or	s2, s2, t0
	sfence.vma
	csrw	satp, s2

	.align 2
va:
#ifndef __CHERI__
	/* Set the global pointer again, this time with the virtual address. */
.option push
.option norelax
	lla	gp, __global_pointer$
.option pop
#else
	/* Create a reduced PCC. */
	li	t0, KERNBASE
	llc	PTR(t1), _C_LABEL(_end)
	sub	t2, t1, t0
	scaddr	PTR(t1), PTR(t1), t0
	scbndsr	PTR(t1), PTR(t1), t2
	llc	PTR(t0), 1f
	scaddr	PTR(t1), PTR(t1), t0
	jr	PTR(t1)
1:
#endif

	/* Set the trap vector to the real handler. */
	LLA_PTR	PTR(t0), cpu_exception_handler
	csrw	PTR_CSR(stvec), PTR(t0)

	/* Ensure sscratch is zero */
	MV_PTR	PTR(t0), PTR_NULL
	csrw	PTR_CSR(sscratch), PTR(t0)

#ifdef __CHERI__
	/* Initialize stack pointer */
	llc	PTR(s2), initstack
	llc	PTR(t0), initstack_end
	sub	t0, t0, s2
	scbndsr	PTR(s2), PTR(s2), t0
	li	t1, CHERI_PERMS_KERNEL_DATA
	acperm	PTR(s2), PTR(s2), t1
	cadd	PTR(sp), PTR(s2), t0

	/* Allocate space for thread0 PCB and riscv_bootparams */
	caddi	PTR(sp), PTR(sp), -(PCB_SIZE + RISCV_BOOTPARAMS_SIZE) & ~STACKALIGNBYTES

	/* Clear BSS */
	llc	PTR(s0), _C_LABEL(__bss_start)
	llc	PTR(s1), _C_LABEL(_end)
1:
	sd	zero, 0(PTR(s0))
	caddi	PTR(s0), PTR(s0), 8
	bltu	s0, s1, 1b

	/* Save omnipotent DDC and clear kernel's DDC. */
	csrr	PTR(s0), ddc
	cmv	PTR(t0), cnull
	csrw	ddc, PTR(t0)

	/* Initialize cap relocs. */
	li	t0, CHERI_PERMS_KERNEL_DATA
	llc	PTR(a0), _C_LABEL(__start___cap_relocs)
	acperm	PTR(a0), PTR(a0), t0
	llc	PTR(a1), _C_LABEL(__stop___cap_relocs)
	sub	t1, a1, a0
	scbndsr	PTR(a0), PTR(a0), t1
	cadd	PTR(a1), PTR(a0), t1
	acperm	PTR(a2), PTR(s0), t0
	mv	a3, zero
	mv	a4, zero		/* TODO: true for PT_CHERI_PCC */
	llc	PTR(a5), _C_LABEL(kernel_cap_relocs_cb)
	scmode	PTR(a6), PTR(a5), zero
	call	_C_LABEL(init_linker_file_cap_relocs)

	/* Initialize capabilities. */
	cmv	PTR(a0), PTR(s0)
	call	_C_LABEL(cheri_init_capabilities)

	/* Fill riscv_bootparams */
	sd	s9, RISCV_BOOTPARAMS_KERN_PHYS(PTR(sp))

	sc	PTR(s2), RISCV_BOOTPARAMS_KERN_STACK(PTR(sp))
	sd	s4, RISCV_BOOTPARAMS_DTBP_PHYS(PTR(sp))
	sc	PTR(s3), RISCV_BOOTPARAMS_MODULEP(PTR(sp))

	/* Discard omnipotent cs0. */
	cmv	PTR(s0), cnull

	/* Clear other capabilities no longer needed. */
	cmv	PTR(s1), cnull
	cmv	PTR(s2), cnull
	cmv	PTR(s3), cnull

	li	t0, RISCV_BOOTPARAMS_SIZE
	scbndsr	PTR(a0), PTR(sp), t0
	call	_C_LABEL(initriscv)
	call	_C_LABEL(mi_startup)
#else
	/* Initialize stack pointer */
	la	sp, initstack_end

	/* Clear frame pointer */
	mv	s0, zero

	/* Allocate space for riscv_bootparams */
	addi	sp, sp, -RISCV_BOOTPARAMS_SIZE & ~STACKALIGNBYTES

	/* Clear BSS */
	la	t0, _C_LABEL(__bss_start)
	la	t1, _C_LABEL(_end)
1:
	sd	zero, 0(t0)
	addi	t0, t0, 8
	bltu	t0, t1, 1b

	/* Fill riscv_bootparams */
	sd	s9, RISCV_BOOTPARAMS_KERN_PHYS(sp)

	la	t0, initstack
	sd	t0, RISCV_BOOTPARAMS_KERN_STACK(sp)
	sd	s4, RISCV_BOOTPARAMS_DTBP_PHYS(sp)
	sd	s3, RISCV_BOOTPARAMS_MODULEP(sp)

	mv	a0, sp
	call	_C_LABEL(initriscv)	/* Off we go */
	call	_C_LABEL(mi_startup)
#endif

	/* We should never reach here, but if so just hang. */
2:
	wfi
	j	2b

/*
 * Get the physical address the kernel is loaded to. Returned in s9.
 */
get_physmem:
	LLA_PTR	PTR(t0), virt_map	/* physical address of virt_map */
	ld	t1, 0(PTR(t0))	/* virtual address of virt_map */
	sub	t1, t1, t0	/* calculate phys->virt delta */
	li	t2, KERNBASE
	sub	s9, t2, t1	/* s9 = physmem base */
	ret

/*
 * T-HEAD CPUs implement an alternate scheme for PTE attributes that is
 * incompatible with the RISC-V PTE specification (see the definitions in
 * pte.h). Worse, it defines a non-zero value for "main" memory, and this must
 * be set in order to proceed with our new page tables.
 *
 * Therefore, we are forced to check the CPU identity here, which is both
 * inconvenient and fragile.
 *
 * Return the required attribute bits in s8. For sane implementations this is
 * zero.
 */
get_pte_fixup_bits:
	mv	s8, zero
	SBI_CALL(SBI_EXT_ID_BASE, SBI_BASE_GET_MVENDORID)
	li	t0, MVENDORID_THEAD
	xor	t0, t0, a1
	bnez	t0, 1f		/* branch if a1 != t0 */
	li	s8, PTE_THEAD_MA_NONE
1:
	ret

	.align  4
initstack:
	.space  (PAGE_SIZE * KSTACK_PAGES)
initstack_end:

/*
 * Static space for the bootstrap page tables. Unused after pmap_bootstrap().
 */
	.balign	PAGE_SIZE
bootstrap_pt_l1:
	.space	PAGE_SIZE
bootstrap_pt_l2:
	.space	PAGE_SIZE

	.align 3
virt_map:
	.quad   virt_map
hart_lottery:
	.space	4

#ifndef SMP
ENTRY(mpentry)
1:
	wfi
	j	1b
END(mpentry)
#else
/*
 * mpentry(unsigned long)
 *
 * Called by a core when it is being brought online.
 */
ENTRY(mpentry)
#ifdef __CHERI__
.option push
.option nocapmode
	modesw.cap
.option pop
#endif
	/*
	 * Calculate the offset to __riscv_boot_ap
	 * for the current core, cpuid is in a0.
	 */
	li	t1, 4
	mulw	t1, t1, a0

	LLA_PTR	PTR(t0), __riscv_boot_ap
	ADD_PTR	PTR(t0), PTR(t0), t1

1:
	/* Wait the kernel to be ready */
	lw	t1, 0(PTR(t0))
	beqz	t1, 1b

	/* Setup stack pointer */
	LLA_PTR	PTR(t0), bootstack
	L_PTR	PTR(sp), 0(PTR(t0))

	/* Get the kernel's load address */
	jal	get_physmem

	/*
	 * Set the supervisor trap vector temporarily. Enabling virtual memory
	 * may generate a page fault. We simply wish to continue onwards, so
	 * have the trap deliver us to 'mpva'.
	 */
	LLA_PTR	PTR(t0), mpva
	li	t1, KERNBASE
	sub	t1, t1, s9
	ADD_PTR	PTR(t0), PTR(t0), t1
	csrw	PTR_CSR(stvec), PTR(t0)

	/* Set page tables base register */
	LLA_PTR	PTR(t2), kernel_pmap_store
	ld	s2, PM_SATP(PTR(t2))
	sfence.vma
	csrw	satp, s2

	.align 2
mpva:
	/* Set the global pointer again, this time with the virtual address. */
#ifdef __CHERI__
	/* CHERI-RISC-V purecap doesn't currently use cgp. */
	cmv	PTR(gp), PTR_NULL
#else
.option push
.option norelax
	lla	gp, __global_pointer$
.option pop
#endif

#ifdef __CHERI__
	/* Create a reduced PCC. */
	li	t0, KERNBASE
	llc	PTR(t1), _C_LABEL(_end)
	sub	t2, t1, t0
	scaddr	PTR(t1), PTR(t1), t0
	scbndsr	PTR(t1), PTR(t1), t2
	llc	PTR(t0), 1f
	scaddr	PTR(t1), PTR(t1), t0
	jr	PTR(t1)
1:
#endif

	/* Set the trap vector to the real handler. */
	LLA_PTR	PTR(t0), cpu_exception_handler
	csrw	PTR_CSR(stvec), PTR(t0)

	/* Ensure sscratch is zero */
	MV_PTR	PTR(t0), PTR_NULL
	csrw	PTR_CSR(sscratch), PTR(t0)

	call	init_secondary
END(mpentry)
#endif
